"
Je représente une enchère
Suivant la séquence d'enchère je fixe la zone de force, le type de distribution, et si possible la répartition par couleur (et autres à préciser) qui définissent la main visible par les autres joueurs.
UnT ouverture: aMain
aMain mainP: self classe ouverture

"
Class {
	#name : 'Bid',
	#superclass : 'Object',
	#instVars : [
		'force',
		'distribution',
		'suits'
	],
	#category : 'Bridge-DDS',
	#package : 'Bridge-DDS'
}
